supermanut/manuti/urls.py
from views import IndexManutiTemplateView, RegistroCreateView, RegistroDeleteView, RegistroListView, \
    RegistroUpdateView, EquipamentoCreateView, EquipamentoDeleteView, EquipamentoListView, EquipamentoUpdateView, \
    AeronaveListView, EquipamentoAeronaveListView, EquipamentoAeronaveDeleteView, AeronaveRegistroListView, RegistroAeronaveListView, \
    AtividadeManutiTemplateView, CombsListView, SilomsListView, UsuarioCreateView, CombsResolvidoUpdateView, SilomsResolvidoUpdateView, \
    EmergenciaCreateView, EmergenciaListView, EmergenciaResolvidoUpdateView, EmergenciaUpdateView, SuprimentoCreateView, \
    SuprimentoDeleteView, SuprimentoListView, SuprimentoUpdateView, FerramentaCreateView, FerramentaDeleteView, FerramentaListView, \
    FerramentaUpdateView, PanesTemplateView
     

from django.conf.urls import url
from . import views


app_name = 'manuti'

urlpatterns = [
    # GET /
    
    #path('', IndexTemplateView.as_view(), name="index"),
    url(r'^$', IndexManutiTemplateView.as_view(), name="index"),
    
    
    url(r'^atividademanuti/', AtividadeManutiTemplateView.as_view(), name="atividade_manuti"),

    # GET /registro/cadastrar    
  
    url(r'^registro/cadastrar', RegistroCreateView.as_view(), name="cadastra_registro"),
    # GET /registros   
    url(r'^registros/', RegistroListView.as_view(), name="lista_registros"),
    # GET/POST /registro/{pk}    
    url(r'^registro/(?P<pk>[0-9]+)/$', RegistroUpdateView.as_view(), name="atualiza_registro"),
    # GET/POST /registros/excluir/{pk}
    url(r'^registro/excluir/(?P<pk>[0-9]+)/$', RegistroDeleteView.as_view(), name="deleta_registro"),

#-----------------------------------------------------------------------------------------------------
    
    # GET /equipamento/cadastrar    
    url(r'^equipamento/cadastrar', EquipamentoCreateView.as_view(), name="cadastra_equipamento"),
    # GET /equipamentos   
    url(r'^equipamentos/', EquipamentoListView.as_view(), name="lista_equipamentos"),
    # GET/POST /equipamento/{pk}    
    url(r'^equipamento/(?P<pk>[0-9]+)/$', EquipamentoUpdateView.as_view(), name="atualiza_equipamento"),
    # GET/POST /equipamentos/excluir/{pk}
    url(r'^equipamento/excluir/(?P<pk>[0-9]+)/$', EquipamentoDeleteView.as_view(), name="deleta_equipamento"),


#-----------------------------------------------------------------------------------------------------
    
# GET /usuario/cadastrar    
    url(r'^usuario/cadastrar', UsuarioCreateView.as_view(), name="cadastra_usuario"),

#-------------------------------------------------------------------------------------------------------------
# Equipamentos em Aeronave
    url(r'^aeronaves/', AeronaveListView.as_view(), name="lista_aeronaves"),  
    
    url(r'^visualizaanvs/', AeronaveRegistroListView.as_view(), name="lista_regaeronaves"),  
    
    url(r'^equipamentoanvs/(?P<fk>[0-9]+)/$', EquipamentoAeronaveListView.as_view(), name="lista_equipamentos_aeronave"),

    # GET/POST /equipamentosem Aeronave/excluir/{pk}
    url(r'^equipamentoanvsdelete/excluir/(?P<pk>[0-9]+)/$', EquipamentoAeronaveDeleteView.as_view(), name="deleta_equipamentoanv"),

    url(r'^registroanvs/(?P<fk>[0-9]+)/$', RegistroAeronaveListView.as_view(), name="lista_registros_aeronave"),
   
    # resolve siloms
    url(r'^silomsresol/(?P<pk>[0-9]+)/$', SilomsResolvidoUpdateView.as_view(), name="resolvesiloms"),
    url(r'^siloms', SilomsListView.as_view(), name="siloms"),
    
    # resolve combs
    url(r'^combsresol/(?P<pk>[0-9]+)/$', CombsResolvidoUpdateView.as_view(), name="resolvecombs"),
    url(r'^combs/', CombsListView.as_view(), name="combs"),
    
    # Emergencias
    # GET /emergencia/cadastrar    
    url(r'^emergencia/cadastrar', EmergenciaCreateView.as_view(), name="cadastra_emergencia"),

    # GET /lista de emergencias
    url(r'^emergenciasresol/(?P<pk>[0-9]+)/$', EmergenciaResolvidoUpdateView.as_view(), name="resolveemergencia"),  
    url(r'^emergencias/', EmergenciaListView.as_view(), name="emergencias"),

     # GET/POST /emergencia/{pk}    
    url(r'^emergencia/(?P<pk>[0-9]+)/$', EmergenciaUpdateView.as_view(), name="atualiza_emergencia"),

     # GET /suprimento/cadastrar    
    url(r'^suprimento/cadastrar', SuprimentoCreateView.as_view(), name="cadastra_suprimento"),
    # GET /suprimentos   
    url(r'^suprimentos/', SuprimentoListView.as_view(), name="lista_suprimento"),
    # GET/POST /suprimento/{pk}    
    url(r'^suprimento/(?P<pk>[0-9]+)/$', SuprimentoUpdateView.as_view(), name="atualiza_suprimento"),
    # GET/POST /suprimento/excluir/{pk}
    url(r'^suprimento/excluir/(?P<pk>[0-9]+)/$', SuprimentoDeleteView.as_view(), name="deleta_suprimento"),

     # GET /ferramenta/cadastrar    
    url(r'^ferramenta/cadastrar', FerramentaCreateView.as_view(), name="cadastra_ferramenta"),
    # GET /ferramenta   
    url(r'^ferramentas/', FerramentaListView.as_view(), name="ferramentas"),
    # GET/POST /ferramenta/{pk}    
    url(r'^ferramenta/(?P<pk>[0-9]+)/$', FerramentaUpdateView.as_view(), name="atualiza_ferramenta"),
    # GET/POST /ferramenta/excluir/{pk}
    url(r'^ferramenta/excluir/(?P<pk>[0-9]+)/$', FerramentaDeleteView.as_view(), name="deleta_ferramenta"),

    url(r'^panes/', PanesTemplateView.as_view(), name="panes"),

]

supermanut/supermanut/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from manuti.views import IndexManutiTemplateView



urlpatterns = [
    
    url(r'^admin/', admin.site.urls),
    url(r'accounts/', include('django.contrib.auth.urls')),
    url(r'^$', IndexManutiTemplateView.as_view(), name="index"),
    url(r'manuti/', include("manuti.urls", namespace='manuti')),
     
    
]

supermanut/manuti/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals


from annoying.decorators import render_to

# Create your views here.

from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, UpdateView, CreateView, DeleteView, DetailView, RedirectView
from manuti.models import RegistroDeManut, Equipamento, Aeronave, UsuarioMarcafut, Emergencia, Suprimento, Ferramenta, CodigoPane
from forms import InsereRegistroForm, InsereEquipamentoForm, InsereUsuarioForm, InsereEmergenciaForm, InsereSuprimentoForm, \
InsereFerramentaForm, InserePaneForm
from bootstrap_modal_forms.mixins import PassRequestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, HttpResponse
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.db.models import Q
from django.shortcuts import get_object_or_404



#PÁGINA PRINCIPAL
# ----------------------------------------------

class IndexManutiTemplateView(TemplateView):
    
       
    activeferramenta = ''
    activeemergencia = ''
    activesiloms = ''
    activeatividade = ''
    activeusuario = ''
    activeindex = 'active'
    activepane = ''

    template_name = "manuti/index.html"

    def get_context_data(self, **kwargs):
        
        context = super(IndexManutiTemplateView, self).get_context_data(**kwargs)
        context['registros'] = len(RegistroDeManut.objetos.all())
        context['aeronaves'] = len(Aeronave.objetos.all())
        context['siloms'] = len(RegistroDeManut.objetos.filter(resolvesiloms=True))
        context['sil'] = len(RegistroDeManut.objetos.all())
        context['emergencias'] = len(Emergencia.objetos.filter(resolveemergencia=True))
        context['emer'] = len(Emergencia.objetos.all())
        context['equipamentos'] = len(Equipamento.objetos.all())
        return context

@method_decorator(login_required, name='dispatch')        
class AtividadeManutiTemplateView(TemplateView, LoginRequiredMixin):
    activeferramenta = ''
    activeemergencia = ''
    activesiloms = ''
    activeatividade = 'active'
    activeusuario = ''
    activeindex = ''
    activepane = ''

    template_name = "manuti/atividademanuti.html"
    context_object_name = "atividademanuti"

# LISTA DE Registros
# ----------------------------------------------

@method_decorator(login_required, name='dispatch')
class RegistroListView(LoginRequiredMixin, ListView):
    
    activeferramenta = ''
    activecombs = ''
    activesiloms = ''
    activeatividade = 'active'
    activeusuario = ''
    activeindex = ''
    activepane = ''

    template_name = "manuti/lista.html"
    #model = RegistroDeManut
    context_object_name = "registros"
    #queryset = RegistroDeManut.objetos.order_by('-data')
    def get_queryset(self):
        
        #Funcionando com filtro por usuário
        #registros = RegistroDeManut.objetos.filter(usuario=self.request.user).order_by('-data')
        #teste = self.request.user.groups.all()
        #print teste, 'xxxxxxxxxxxx'

        busca = self.request.GET.get('search')

        if busca:
            registros = RegistroDeManut.objetos.filter(Q(data__icontains=busca) | Q(titulo__icontains=busca) | Q(ocorrencia__icontains=busca) | Q(solucao__icontains=busca), \
                usuario=self.request.user).order_by('-data')
        else:
            registros = RegistroDeManut.objetos.filter(usuario=self.request.user).order_by('-data')

        
        return registros
    

# CADASTRAMENTO DE Registro
# ----------------------------------------------

@method_decorator(login_required, name='dispatch')
class RegistroCreateView(LoginRequiredMixin,CreateView):
    
    activeferramenta = ''
    activecombs = ''
    activesiloms = ''
    activeatividade = 'active'
    activeusuario = ''
    activeindex = ''
    activepane = ''

    template_name = "manuti/cria.html"
    model = RegistroDeManut
    form_class = InsereRegistroForm
    success_url = reverse_lazy("manuti:atividade_manuti")
    def form_valid(self, form):
        form.instance.usuario = self.request.user
        return super(RegistroCreateView, self).form_valid(form)
    

      


# ATUALIZAÇÃO DE Registros
# ----------------------------------------------
@method_decorator(login_required, name='dispatch')
class RegistroUpdateView(UpdateView, LoginRequiredMixin):
    
    activeferramenta = ''
    activeemergencia = ''
    activesiloms = ''
    activeatividade = 'active'
    activeusuario = ''
    activeindex = ''
    activepane = ''

    template_name = "manuti/atualiza.html"
    model = RegistroDeManut
    form_class = InsereRegistroForm
    context_object_name = 'registro'
    success_url = reverse_lazy("manuti:lista_registros")
    def form_valid(self, form):
        form.instance.usuario = self.request.user
        return super(RegistroUpdateView , self).form_valid(form)


# EXCLUSÃO DE Registros
# ----------------------------------------------
@method_decorator(login_required, name='dispatch')
class RegistroDeleteView(DeleteView, LoginRequiredMixin):
    
    activeferramenta = ''
    activeemergencia = ''
    activesiloms = ''
    activeatividade = 'active'
    activeusuario = ''
    activeindex = ''
    activepane = ''

    template_name = "manuti/exclui.html"
    model = RegistroDeManut
    fields = '__all__'
    context_object_name = 'registro'
    success_url = reverse_lazy("manuti:lista_registros")

#------------------------------------------------------------------------------------------------------

# LISTA DE Equipamentos
# ----------------------------------------------
@method_decorator(login_required, name='dispatch')
class EquipamentoListView(ListView, LoginRequiredMixin):
    
    activeferramenta = ''
    activeemergencia = ''
    activesiloms = ''
    activeatividade = 'active'
    activeusuario = ''
    activeindex = ''
    activepane = ''

    template_name = "manuti/listaEquipamento.html"
    #model = Equipamento
    context_object_name = "equipamentos"
    #queryset = Equipamento.objetos.order_by('-id')
    def get_queryset(self):

        busca = self.request.GET.get('search')

        if busca:
            equipamentos = Equipamento.objetos.filter(Q(nome__icontains=busca) | Q(serialnumber__icontains=busca) | Q(partnumber__icontains=busca), \
                usuario=self.request.user).order_by('-id')
        else:
            equipamentos = Equipamento.objetos.filter(usuario=self.request.user).order_by('-id')

        return equipamentos
    

# CADASTRAMENTO DE Equipamentos
# ----------------------------------------------
@method_decorator(login_required, name='dispatch')
class EquipamentoCreateView(CreateView, LoginRequiredMixin):
    
    activeferramenta = ''
    activeemergencia = ''
    activesiloms = ''
    activeatividade = 'active'
    activeusuario = ''
    activeindex = ''
    activepane = ''

    template_name = "manuti/criaEquipamento.html"
    model = Equipamento
    form_class = InsereEquipamentoForm
    success_url = reverse_lazy("manuti:lista_equipamentos")
    def form_valid(self, form):
        form.instance.usuario = self.request.user
        return super(EquipamentoCreateView, self).form_valid(form)


# ATUALIZAÇÃO DE Equipamentos
# ----------------------------------------------
@method_decorator(login_required, name='dispatch')
class EquipamentoUpdateView(UpdateView, LoginRequiredMixin):
    
    activeferramenta = ''
    activeemergencia = ''
    activesiloms = ''
    activeatividade = 'active'
    activeusuario = ''
    activeindex = ''
    activepane = ''

    template_name = "manuti/atualizaEquipamento.html"
    model = Equipamento
    form_class = InsereEquipamentoForm
    context_object_name = 'equipamento'
    success_url = reverse_lazy("manuti:atividade_manuti")
    def form_valid(self, form):
        form.instance.usuario = self.request.user
        return super(EquipamentoUpdateView, self).form_valid(form)


# EXCLUSÃO DE Equipamentos
# ----------------------------------------------
@method_decorator(login_required, name='dispatch')
class EquipamentoDeleteView(DeleteView, LoginRequiredMixin):
    
    activeferramenta = ''
    activeemergencia = ''
    activesiloms = ''
    activeatividade = 'active'
    activeusuario = ''
    activeindex = ''
    activepane = ''

    template_name = "manuti/excluiEquipamento.html"
    model = Equipamento
    fields = '__all__'
    context_object_name = 'equipamento'
    success_url = reverse_lazy("manuti:lista_equipamentos")

#------------------------------------------------------------------------------------------------------

# LISTA DE Aeronaves
# ----------------------------------------------

class AeronaveListView(ListView, LoginRequiredMixin):
    
    activeferramenta = ''
    activeemergencia = ''
    activesiloms = ''
    activeatividade = 'active'
    activeusuario = ''
    activeindex = ''
    activepane = ''

    template_name = "manuti/listaAnv.html"
    #model = Aeronave
    context_object_name = "aeronaves"
    queryset = Aeronave.objetos.order_by('matricula')

@method_decorator(login_required, name='dispatch')
class AeronaveRegistroListView(ListView, LoginRequiredMixin):
    
    activeferramenta = ''
    activeemergencia = ''
    activesiloms = ''
    activeatividade = 'active'
    activeusuario = ''
    activeindex = ''
    activepane = ''

    template_name = "manuti/visualizaanv.html"
    #model = Aeronave

supermanut/manuti/templates/manuti/_layouts/baselogin.html
<!doctype html>
<html lang="pt-br">
{% load static %}
<head>
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href= "{% static '/manuti/img/favicon.png'%}">
  <link rel="icon" type="image/png" href="{% static '/manuti/img/favicon.png'%}">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>{% block title %}Sistema de Gerenciamento de Atividades de Manutenção{% endblock %}</title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
  <!-- CSS Files -->
  <link href="{% static '/assets/css/material-dashboard.css'%}" rel="stylesheet" />
  <link rel="stylesheet" href="{% static 'assets/css/bootstrap.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

  {% block styles %}{% endblock %}
</head>

<body class="">
  <div class="wrapper ">
    <div class="sidebar" data-color="green" data-background-color="white">
      <!--
        Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"

        Tip 2: you can also add an image using data-image tag
    -->
      <div class="logo">
          <a class="navbar-brand" href="{% url 'manuti:index' %}">
              <img src="{% static 'manuti/img/favicon.png' %}" height="45px">
            </a>
        <class="simple-text logo-normal">
          SuperManuTI</class>     
      </div>
      
    </div>
    <div class="main-panel">
      
      <!-- Navbar -->
      {% comment %} <nav class="navbar navbar-expand-lg navbar navbar-dark bg-success">
         
          
         
      </nav> {% endcomment %}

      <nav class="navbar navbar-expand-lg navbar navbar-dark bg-success fixed-top">
          <div class="container col-md-12">
            <div class="navbar-wrapper">
                
              <a class="navbar-brand"  href="{% url 'manuti:index' %}"><h3>SuperManuTI</h3></a>
              <i class="material-icons">build</i>
            </div>
            

            

               
            </div> 
          </div>
        </nav>
      <!-- End Navbar -->
      
          <!-- Texto para comprovar autenticação -->
          <div class="container-fluid mt-5">
          </br>
          
  

          <!-- your content here -->
          {% block conteudo %}{% endblock %}

        </div>
      
      
    </div>
  </div>
  <!--   Core JS Files   -->
  <script src="{% static '/assets/js/core/jquery.min.js'%}" type="text/javascript"></script>
  <script src="{% static '/assets/js/core/popper.min.js'%}" type="text/javascript"></script>
  <script src="{% static '/assets/js/core/bootstrap-material-design.min.js'%}" type="text/javascript"></script>
  <script src="{% static '/assets/js/plugins/perfect-scrollbar.jquery.min.js'%}"></script>
  <!--  Google Maps Plugin    -->
  <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
  <!-- Chartist JS -->
  <script src="{% static '/assets/js/plugins/chartist.min.js'%}"></script>
  <!--  Notifications Plugin    -->
  <script src="{% static '/assets/js/plugins/bootstrap-notify.js'%}"></script>
  <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{% static '/assets/js/material-dashboard.min.js'%}" type="text/javascript"></script>

  <script src="{% static '/manuti/js/bootstrap.min.js' %}"></script>
  <script src="{% static '/manuti/js/jquery.min.js' %}"></script>
  <!--<script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>
   You can alternatively load the minified version 
  <script src="{% static 'js/jquery.bootstrap.modal.forms.min.js' %}"></script>-->
</body>

</html>

supermanut/manuti/templates/manuti/_layouts/indexMaterial.html
<!doctype html>
<html lang="pt-br">
{% load static %}
<head>
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href= "{% static '/manuti/img/favicon.png'%}">
  <link rel="icon" type="image/png" href="{% static '/manuti/img/favicon.png'%}">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>{% block title %}Sistema de Gerenciamento de Atividades de Manutenção{% endblock %}</title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
  <!-- CSS Files -->
  <link href="{% static '/assets/css/material-dashboard.css'%}" rel="stylesheet" />
  <link rel="stylesheet" href="{% static 'assets/css/bootstrap.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">

  {% block styles %}{% endblock %}
</head>

<body class="">
  <div class="wrapper ">
    <div class="sidebar" data-color="green" data-background-color="white">
      <!--
        Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"

        Tip 2: you can also add an image using data-image tag
    -->
      <div class="logo">
          <a class="navbar-brand" href="{% url 'manuti:index' %}">
              <img src="{% static 'manuti/img/favicon.png' %}" height="45px">
            </a>
        <class="simple-text logo-normal">
          SuperManuTI</class>     
      </div>
      <div class="sidebar-wrapper">
        <ul class="nav">
          <li class="nav-item {{view.activeindex}}  ">
            <a class="nav-link" href="{% url 'manuti:index' %}">
              <i class="material-icons">dashboard</i>
              <p>DashBoard</p>
            </a>
          </li>
          <!-- your sidebar here 
                <li class="nav-item {{view.activeusuario}}">
                  <a class="nav-link" href="#">
                    <i class="material-icons">person</i>
                    <p>Usuário</p>
                  </a>-->
                </li> 
                <li class="nav-item {{view.activeatividade}}">
                  <a class="nav-link" href="{% url 'manuti:atividade_manuti' %}">
                    <i class="material-icons">miscellaneous_services</i>
                    <p>Manutenção</p>
                  </a>
                </li>                
                <li class="nav-item {{view.activesiloms}}">
                  <a class="nav-link" href="{% url 'manuti:siloms' %}">
                    <i class="material-icons">gavel</i>
                    <p>Siloms</p>
                  </a>
                </li>
                <li class="nav-item {{view.activeemergencia}}">
                    <a class="nav-link" href="{% url 'manuti:emergencias' %}">
                      <i class="material-icons">warning</i>
                      <p>Emergências</p>
                    </a>
                  </li>
                <li class="nav-item {{view.activeferramenta}}">
                    <a class="nav-link" href="{% url 'manuti:ferramentas' %}">
                      <i class="material-icons">handyman</i>
                      <p>Ferramentas</p>
                    </a>
                  </li>
                  <li class="nav-item {{view.activepane}}">
                    <a class="nav-link" href="{% url 'manuti:panes' %}">
                      <i class="material-icons">bug_report</i>
                      <p>MFL</p>
                    </a>
                  </li>
                {% comment %} <li class="nav-item ">
                  <a class="nav-link" href="./notifications.html">
                    <i class="material-icons">notifications</i>
                    <p>Notifications</p>
                  </a>
                </li> {% endcomment %}

        </ul>
      </div>
    </div>

    
      <!-- Navbar -->
  <div class="main-panel">

    <nav class="navbar navbar-expand-lg navbar-dark bg-success">

      <button class="navbar-toggler" type="button" 
      data-toggle="collapse" data-target="#navbarSupportedContent" 
      aria-controls="navbarSupportedContent" aria-expanded="false" 
      aria-label="Toggle navigation">
      <font color = "#fff"><i class="material-icons">menu</i></font>
  </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">

              {% if user.is_authenticated %}
            <p class="logged-in-p">
                Olá {{ user.username }} seja bem vindo  
                <span class="Sair"><a href="{% url 'logout' %}"> <font color = "#0c4003">| Sair | </font> </a></span>
            </p>
              {% endif %}
           
          </li>
          <li class="nav-item">
            
          </li>
          <li class="nav-item dropdown">
            
          </li>
          <li class="nav-item">
            
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          
          <!-- <input class="form-control mr-sm-2" type="search" placeholder="Pesquisar" aria-label="Search">
          <button class="btn btn-outline-dark my-2 my-sm-0" type="submit">Buscar</button> -->
        </form>
        
      </div>
    </nav>
      <!-- End Navbar -->
            <div class="col-md-12">
                        <!-- your content here -->
              {% block conteudo %}{% endblock %}

            </div>

        
      
      <footer class="footer">
        <div class="container-fluid">
          <nav class="float-left">
            <ul>
              <li>
                
              </li>
            </ul>
          </nav>
          <div class="copyright float-right">
            &copy;
            <script>
              document.write(new Date().getFullYear())
            </script>, Portal Goiano <i class="material-icons">nature_people</i> 
          </div>
          <!-- your footer here -->
        </div>
      </footer>
    </div>
    </div>
  </div>
  <!--   Core JS Files   -->
  <script src="{% static '/assets/js/core/jquery.min.js'%}" type="text/javascript"></script>
  <script src="{% static '/assets/js/core/popper.min.js'%}" type="text/javascript"></script>
  <script src="{% static '/assets/js/core/bootstrap-material-design.min.js'%}" type="text/javascript"></script>
  <script src="{% static '/assets/js/plugins/perfect-scrollbar.jquery.min.js'%}"></script>
  <!--  Google Maps Plugin    -->
  <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
  <!-- Chartist JS -->
  <script src="{% static '/assets/js/plugins/chartist.min.js'%}"></script>
  <!--  Notifications Plugin    -->
  <script src="{% static '/assets/js/plugins/bootstrap-notify.js'%}"></script>
  <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{% static '/assets/js/material-dashboard.min.js'%}" type="text/javascript"></script>

  <script src="{% static '/manuti/js/bootstrap.min.js' %}"></script>
  <script src="{% static '/manuti/js/jquery.min.js' %}"></script>

  <!--<script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>
   You can alternatively load the minified version 
  <script src="{% static 'js/jquery.bootstrap.modal.forms.min.js' %}"></script>-->
</body>

</html>