supermanut/manuti/urls.py
from views import IndexManutiTemplateView, RegistroCreateView, RegistroDeleteView, RegistroListView, \
    RegistroUpdateView, EquipamentoCreateView, EquipamentoDeleteView, EquipamentoListView, EquipamentoUpdateView, \
    AeronaveListView, EquipamentoAeronaveListView, EquipamentoAeronaveDeleteView, AeronaveRegistroListView, RegistroAeronaveListView, \
    AtividadeManutiTemplateView, CombsListView, SilomsListView, UsuarioCreateView, CombsResolvidoUpdateView, SilomsResolvidoUpdateView, \
    EmergenciaCreateView, EmergenciaListView, EmergenciaResolvidoUpdateView, EmergenciaUpdateView, SuprimentoCreateView, \
    SuprimentoDeleteView, SuprimentoListView, SuprimentoUpdateView, FerramentaCreateView, FerramentaDeleteView, FerramentaListView, \
    FerramentaUpdateView, PanesTemplateView
     

from django.conf.urls import url
from . import views


app_name = 'manuti'

urlpatterns = [
    # GET /
    
    #path('', IndexTemplateView.as_view(), name="index"),
    url(r'^$', IndexManutiTemplateView.as_view(), name="index"),
    
    
    url(r'^atividademanuti/', AtividadeManutiTemplateView.as_view(), name="atividade_manuti"),

    # GET /registro/cadastrar    
  
    url(r'^registro/cadastrar', RegistroCreateView.as_view(), name="cadastra_registro"),
    # GET /registros   
    url(r'^registros/', RegistroListView.as_view(), name="lista_registros"),
    # GET/POST /registro/{pk}    
    url(r'^registro/(?P<pk>[0-9]+)/$', RegistroUpdateView.as_view(), name="atualiza_registro"),
    # GET/POST /registros/excluir/{pk}
    url(r'^registro/excluir/(?P<pk>[0-9]+)/$', RegistroDeleteView.as_view(), name="deleta_registro"),

#-----------------------------------------------------------------------------------------------------
    
    # GET /equipamento/cadastrar    
    url(r'^equipamento/cadastrar', EquipamentoCreateView.as_view(), name="cadastra_equipamento"),
    # GET /equipamentos   
    url(r'^equipamentos/', EquipamentoListView.as_view(), name="lista_equipamentos"),
    # GET/POST /equipamento/{pk}    
    url(r'^equipamento/(?P<pk>[0-9]+)/$', EquipamentoUpdateView.as_view(), name="atualiza_equipamento"),
    # GET/POST /equipamentos/excluir/{pk}
    url(r'^equipamento/excluir/(?P<pk>[0-9]+)/$', EquipamentoDeleteView.as_view(), name="deleta_equipamento"),


#-----------------------------------------------------------------------------------------------------
    
# GET /usuario/cadastrar    
    url(r'^usuario/cadastrar', UsuarioCreateView.as_view(), name="cadastra_usuario"),

#-------------------------------------------------------------------------------------------------------------
# Equipamentos em Aeronave
    url(r'^aeronaves/', AeronaveListView.as_view(), name="lista_aeronaves"),  
    
    url(r'^visualizaanvs/', AeronaveRegistroListView.as_view(), name="lista_regaeronaves"),  
    
    url(r'^equipamentoanvs/(?P<fk>[0-9]+)/$', EquipamentoAeronaveListView.as_view(), name="lista_equipamentos_aeronave"),

    # GET/POST /equipamentosem Aeronave/excluir/{pk}
    url(r'^equipamentoanvsdelete/excluir/(?P<pk>[0-9]+)/$', EquipamentoAeronaveDeleteView.as_view(), name="deleta_equipamentoanv"),

    url(r'^registroanvs/(?P<fk>[0-9]+)/$', RegistroAeronaveListView.as_view(), name="lista_registros_aeronave"),
   
    # resolve siloms
    url(r'^silomsresol/(?P<pk>[0-9]+)/$', SilomsResolvidoUpdateView.as_view(), name="resolvesiloms"),
    url(r'^siloms', SilomsListView.as_view(), name="siloms"),
    
    # resolve combs
    url(r'^combsresol/(?P<pk>[0-9]+)/$', CombsResolvidoUpdateView.as_view(), name="resolvecombs"),
    url(r'^combs/', CombsListView.as_view(), name="combs"),
    
    # Emergencias
    # GET /emergencia/cadastrar    
    url(r'^emergencia/cadastrar', EmergenciaCreateView.as_view(), name="cadastra_emergencia"),

    # GET /lista de emergencias
    url(r'^emergenciasresol/(?P<pk>[0-9]+)/$', EmergenciaResolvidoUpdateView.as_view(), name="resolveemergencia"),  
    url(r'^emergencias/', EmergenciaListView.as_view(), name="emergencias"),

     # GET/POST /emergencia/{pk}    
    url(r'^emergencia/(?P<pk>[0-9]+)/$', EmergenciaUpdateView.as_view(), name="atualiza_emergencia"),

     # GET /suprimento/cadastrar    
    url(r'^suprimento/cadastrar', SuprimentoCreateView.as_view(), name="cadastra_suprimento"),
    # GET /suprimentos   
    url(r'^suprimentos/', SuprimentoListView.as_view(), name="lista_suprimento"),
    # GET/POST /suprimento/{pk}    
    url(r'^suprimento/(?P<pk>[0-9]+)/$', SuprimentoUpdateView.as_view(), name="atualiza_suprimento"),
    # GET/POST /suprimento/excluir/{pk}
    url(r'^suprimento/excluir/(?P<pk>[0-9]+)/$', SuprimentoDeleteView.as_view(), name="deleta_suprimento"),

     # GET /ferramenta/cadastrar    
    url(r'^ferramenta/cadastrar', FerramentaCreateView.as_view(), name="cadastra_ferramenta"),
    # GET /ferramenta   
    url(r'^ferramentas/', FerramentaListView.as_view(), name="ferramentas"),
    # GET/POST /ferramenta/{pk}    
    url(r'^ferramenta/(?P<pk>[0-9]+)/$', FerramentaUpdateView.as_view(), name="atualiza_ferramenta"),
    # GET/POST /ferramenta/excluir/{pk}
    url(r'^ferramenta/excluir/(?P<pk>[0-9]+)/$', FerramentaDeleteView.as_view(), name="deleta_ferramenta"),

    url(r'^panes/', PanesTemplateView.as_view(), name="panes"),

]

supermanut/supermanut/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from manuti.views import IndexManutiTemplateView



urlpatterns = [
    
    url(r'^admin/', admin.site.urls),
    url(r'accounts/', include('django.contrib.auth.urls')),
    url(r'^$', IndexManutiTemplateView.as_view(), name="index"),
    url(r'manuti/', include("manuti.urls", namespace='manuti')),
     
    
]

supermanut/manuti/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals


from annoying.decorators import render_to

# Create your views here.

from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, UpdateView, CreateView, DeleteView, DetailView, RedirectView
from manuti.models import RegistroDeManut, Equipamento, Aeronave, UsuarioMarcafut, Emergencia, Suprimento, Ferramenta, CodigoPane
from forms import InsereRegistroForm, InsereEquipamentoForm, InsereUsuarioForm, InsereEmergenciaForm, InsereSuprimentoForm, \
InsereFerramentaForm, InserePaneForm
from bootstrap_modal_forms.mixins import PassRequestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, HttpResponse
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.db.models import Q
from django.shortcuts import get_object_or_404



#PÁGINA PRINCIPAL
# ----------------------------------------------

class IndexManutiTemplateView(TemplateView):
    
       
    activeferramenta = ''
    activeemergencia = ''
    activesiloms = ''
    activeatividade = ''
    activeusuario = ''
    activeindex = 'active'
    activepane = ''

    template_name = "manuti/index.html"

    def get_context_data(self, **kwargs):
        
        context = super(IndexManutiTemplateView, self).get_context_data(**kwargs)
        context['registros'] = len(RegistroDeManut.objetos.all())
        context['aeronaves'] = len(Aeronave.objetos.all())
        context['siloms'] = len(RegistroDeManut.objetos.filter(resolvesiloms=True))
        context['sil'] = len(RegistroDeManut.objetos.all())
        context['emergencias'] = len(Emergencia.objetos.filter(resolveemergencia=True))
        context['emer'] = len(Emergencia.objetos.all())
        context['equipamentos'] = len(Equipamento.objetos.all())
        return context

@method_decorator(login_required, name='dispatch')        
class AtividadeManutiTemplateView(TemplateView, LoginRequiredMixin):
    activeferramenta = ''
    activeemergencia = ''
    activesiloms = ''
    activeatividade = 'active'
    activeusuario = ''
    activeindex = ''
    activepane = ''

    template_name = "manuti/atividademanuti.html"
    context_object_name = "atividademanuti"

# LISTA DE Registros
# ----------------------------------------------

@method_decorator(login_required, name='dispatch')
class RegistroListView(LoginRequiredMixin, ListView):
    
    activeferramenta = ''
    activecombs = ''
    activesiloms = ''
    activeatividade = 'active'
    activeusuario = ''
    activeindex = ''
    activepane = ''

    template_name = "manuti/lista.html"
    #model = RegistroDeManut
    context_object_name = "registros"
    #queryset = RegistroDeManut.objetos.order_by('-data')
    def get_queryset(self):
        
        #Funcionando com filtro por usuário
        #registros = RegistroDeManut.objetos.filter(usuario=self.request.user).order_by('-data')
        #teste = self.request.user.groups.all()
        #print teste, 'xxxxxxxxxxxx'

        busca = self.request.GET.get('search')

        if busca:
            registros = RegistroDeManut.objetos.filter(Q(data__icontains=busca) | Q(titulo__icontains=busca) | Q(ocorrencia__icontains=busca) | Q(solucao__icontains=busca), \
                usuario=self.request.user).order_by('-data')
        else:
            registros = RegistroDeManut.objetos.filter(usuario=self.request.user).order_by('-data')

        
        return registros
    

# CADASTRAMENTO DE Registro
# ----------------------------------------------

@method_decorator(login_required, name='dispatch')
class RegistroCreateView(LoginRequiredMixin,CreateView):
    
    activeferramenta = ''
    activecombs = ''
    activesiloms = ''
    activeatividade = 'active'
    activeusuario = ''
    activeindex = ''
    activepane = ''

    template_name = "manuti/cria.html"
    model = RegistroDeManut
    form_class = InsereRegistroForm
    success_url = reverse_lazy("manuti:atividade_manuti")
    def form_valid(self, form):
        form.instance.usuario = self.request.user
        return super(RegistroCreateView, self).form_valid(form)
    

      


# ATUALIZAÇÃO DE Registros
# ----------------------------------------------
@method_decorator(login_required, name='dispatch')
class RegistroUpdateView(UpdateView, LoginRequiredMixin):
    
    activeferramenta = ''
    activeemergencia = ''
    activesiloms = ''
    activeatividade = 'active'
    activeusuario = ''
    activeindex = ''
    activepane = ''

    template_name = "manuti/atualiza.html"
    model = RegistroDeManut
    form_class = InsereRegistroForm
    context_object_name = 'registro'
    success_url = reverse_lazy("manuti:lista_registros")
    def form_valid(self, form):
        form.instance.usuario = self.request.user
        return super(RegistroUpdateView , self).form_valid(form)


# EXCLUSÃO DE Registros
# ----------------------------------------------
@method_decorator(login_required, name='dispatch')
class RegistroDeleteView(DeleteView, LoginRequiredMixin):
    
    activeferramenta = ''
    activeemergencia = ''
    activesiloms = ''
    activeatividade = 'active'
    activeusuario = ''
    activeindex = ''
    activepane = ''

    template_name = "manuti/exclui.html"
    model = RegistroDeManut
    fields = '__all__'
    context_object_name = 'registro'
    success_url = reverse_lazy("manuti:lista_registros")

#------------------------------------------------------------------------------------------------------

# LISTA DE Equipamentos
# ----------------------------------------------
@method_decorator(login_required, name='dispatch')
class EquipamentoListView(ListView, LoginRequiredMixin):
    
    activeferramenta = ''
    activeemergencia = ''
    activesiloms = ''
    activeatividade = 'active'
    activeusuario = ''
    activeindex = ''
    activepane = ''

    template_name = "manuti/listaEquipamento.html"
    #model = Equipamento
    context_object_name = "equipamentos"
    #queryset = Equipamento.objetos.order_by('-id')
    def get_queryset(self):

        busca = self.request.GET.get('search')

        if busca:
            equipamentos = Equipamento.objetos.filter(Q(nome__icontains=busca) | Q(serialnumber__icontains=busca) | Q(partnumber__icontains=busca), \
                usuario=self.request.user).order_by('-id')
        else:
            equipamentos = Equipamento.objetos.filter(usuario=self.request.user).order_by('-id')

        return equipamentos
    

# CADASTRAMENTO DE Equipamentos
# ----------------------------------------------
@method_decorator(login_required, name='dispatch')
class EquipamentoCreateView(CreateView, LoginRequiredMixin):
    
    activeferramenta = ''
    activeemergencia = ''
    activesiloms = ''
    activeatividade = 'active'
    activeusuario = ''
    activeindex = ''
    activepane = ''

    template_name = "manuti/criaEquipamento.html"
    model = Equipamento
    form_class = InsereEquipamentoForm
    success_url = reverse_lazy("manuti:lista_equipamentos")
    def form_valid(self, form):
        form.instance.usuario = self.request.user
        return super(EquipamentoCreateView, self).form_valid(form)


# ATUALIZAÇÃO DE Equipamentos
# ----------------------------------------------
@method_decorator(login_required, name='dispatch')
class EquipamentoUpdateView(UpdateView, LoginRequiredMixin):
    
    activeferramenta = ''
    activeemergencia = ''
    activesiloms = ''
    activeatividade = 'active'
    activeusuario = ''
    activeindex = ''
    activepane = ''

    template_name = "manuti/atualizaEquipamento.html"
    model = Equipamento
    form_class = InsereEquipamentoForm
    context_object_name = 'equipamento'
    success_url = reverse_lazy("manuti:atividade_manuti")
    def form_valid(self, form):
        form.instance.usuario = self.request.user
        return super(EquipamentoUpdateView, self).form_valid(form)


# EXCLUSÃO DE Equipamentos
# ----------------------------------------------
@method_decorator(login_required, name='dispatch')
class EquipamentoDeleteView(DeleteView, LoginRequiredMixin):
    
    activeferramenta = ''
    activeemergencia = ''
    activesiloms = ''
    activeatividade = 'active'
    activeusuario = ''
    activeindex = ''
    activepane = ''

    template_name = "manuti/excluiEquipamento.html"
    model = Equipamento
    fields = '__all__'
    context_object_name = 'equipamento'
    success_url = reverse_lazy("manuti:lista_equipamentos")

#------------------------------------------------------------------------------------------------------

# LISTA DE Aeronaves
# ----------------------------------------------

class AeronaveListView(ListView, LoginRequiredMixin):
    
    activeferramenta = ''
    activeemergencia = ''
    activesiloms = ''
    activeatividade = 'active'
    activeusuario = ''
    activeindex = ''
    activepane = ''

    template_name = "manuti/listaAnv.html"
    #model = Aeronave
    context_object_name = "aeronaves"
    queryset = Aeronave.objetos.order_by('matricula')

@method_decorator(login_required, name='dispatch')
class AeronaveRegistroListView(ListView, LoginRequiredMixin):
    
    activeferramenta = ''
    activeemergencia = ''
    activesiloms = ''
    activeatividade = 'active'
    activeusuario = ''
    activeindex = ''
    activepane = ''

    template_name = "manuti/visualizaanv.html"
    #model = Aeronave

supermanut/manuti/templates/manuti/atualizaFerramenta.html
{% extends "manuti/_layouts/indexMaterial.html" %}

{% load widget_tweaks %}

{% block title %}Atualização de Ferramenta{% endblock %}

{% block conteudo %}

  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Atualizar Ferramenta</h5>
          <br>
          <form method="post">
            <!-- Não se esqueça dessa tag -->
            {% csrf_token %}

            <div class = "col-md-12">
                <div class = "row">
  
                 <div class = "col-md-06">
                                 
                  <!-- Nome -->
                  <div class="input-group mb-3">
                      <div class="input-group-prepend">
                        <span class="input-group-text">Equipamento</span>
                      </div>
                      {% render_field form.nome class+="form-control" %}
                    </div>
                    </div>
            
                    <div class = "col-md-06">
                <!-- Descrição -->
                  <div class="input-group mb-3">
                    <div class="input-group-prepend">
                      <span class="input-group-text">Ferramenta:</span>
                    </div>
                    {% render_field form.descricao class+="form-control" %}
                  </div>
                  </div>
                  
              <hr>
              <div class="text-right">
                <a href="{% url 'manuti:ferramentas' %}" class="btn btn-outline-info">Voltar</a>
                <button class="btn btn-success">Enviar</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

supermanut/manuti/templates/manuti/combs.html
{% extends "manuti/_layouts/indexMaterial.html" %}


{% block title %}Lista de Equipamentos{% endblock %}



{% block conteudo %}
        <div class="row">
          <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">Lista de Equipamentos Instalados</h5>
      
                {% if combs|length > 0 %}
                  <p class="card-text">
                    Aqui está a lista dos <code>Ultimos Equipamentos COMBS</code> Instalados.
                  </p>
      
                  <table class="table table-striped" >
                    <thead class="card-header card-header-info">
                        <div class="ct-chart" id="dailySalesChart"></div>
                    <tr>
                      <th scope="col">Aeronave</th>
                      <th scope="col">Nome</th>
                      <th scope="col">PN</th>
                      <th scope="col">SN</th>
                      
                      <th scope="col" class="text-center">Resolver </th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for comb in combs %}
                      <tr>
                        <th scope="row">{{ comb.aeronave }}</th>
                        <td>{{ comb.nome }}</td>
                        <td> {{comb.partnumber }}</td>
                        <td> {{comb.serialnumber }}</td>
                        
                        <td class="text-center">

                          {% if comb.resolvecombs == False %}
                          <a href="{% url 'manuti:resolvecombs' pk=comb.id %}">
                          <button type="button" class="btn btn-danger bmd-btn-fab "> 
                            <i class="material-icons">  thumb_down </i>  
                          </button>
                          </a>{%else%}
                          <a href="{% url 'manuti:resolvecombs' pk=comb.id %}">
                          <button type="button" class="btn btn-success bmd-btn-fab  "> 
                            <i class="material-icons">  thumb_up </i>  
                          </button>
                          </a>{%endif%}              
                         </td>
                      </tr>
                    {% endfor %}
                    </tbody>
                  </table>
              {% else %}
                <div class="text-center mt-5 mb-5 jumbotron">
                  <h5>Nenhum <code>Equipamento</code> instalado ainda.</h5>
                </div>
              {% endif %}
                <hr />
               
              </div>
            </div>
          </div>
        </div>
      

{% endblock %}

supermanut/manuti/templates/manuti/intensanv.html
{% extends "manuti/_layouts/indexMaterial.html" %}


{% block title %}Lista de Equipamentos{% endblock %}

{% load primeira_letra %}

{% block conteudo %}

    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Lista de Registros de Aeronaves</h5>
  
            {% comment %} {% if registro|length > 0 %} {% endcomment %}
              <p class="card-text">
                Aqui está a lista das <code>Aeronaves</code> cadastradas.
              </p>
  
              <table class="table">
                
                <tbody>
                
                  <tr>
                                        
                    <td class="text-center">
                      <a href="{% url 'manuti:lista_equipamentos_aeronave' fk=aeronave.id %}"
                         class="btn btn-success">
                        Visualizar
                      </a>
                      
                    </td>
                      <div class="row">
                        <div class="col-md-4">
                          <div class="card card-chart">
                            <div class="card-header card-header-success">
                              <div class="ct-chart" id="dailySalesChart"></div>
                            </div>
                            <div class="card-body">
                              <h4 class="card-title">{{ aeronave.nome }}</h4>
                              <p class="card-category">
                                  <span class="text-success"><i class="fa fa-flight"></i> 55% </span> increase in today sales.</p>
                            </div>
                            <div class="card-footer">
                              <div class="stats" >
                                <a href="{% url 'manuti:lista_registros_aeronave' fk=aeronave.id %}"
                          class="btn btn-success" "text-center">
                          Visualizar
                        </a>
                              </div>
                            </div>
                          </div>
                        </div>
                        </div>
                  </tr>
               
                </tbody>
              </table>
          {% comment %} {% else %}
            <div class="text-center mt-5 mb-5 jumbotron">
              <h5>Nenhuma <code>Aeronave /code> cadastrada</h5>
            </div>
          {% endif %} {% endcomment %}
            <hr />
            
          </div>
        </div>
      </div>
    </div>


{% endblock %}

supermanut/manuti/templates/manuti/listaFerramenta.html
{% extends "manuti/_layouts/indexMaterial.html" %}


{% block title %}Lista de Ferramentas{% endblock %}



{% block conteudo %}
 

        <div class="row">
          <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
              <div class=" search-div">
                <form method="GET">
                             
                  <input type="text" class="form-control" name="search" id="search" placeholder="PESQUISAR">
                        
                </form>       
              </div>
              <div class="card-body">
                <h5 class="card-title">Lista de Ferramentas</h5>
      
                {% if ferramentas|length > 0 %}
                  <p class="card-text">
                    Aqui está a lista das <code>Ferramentas Cadastradas </code> 
                  </p>
                <div class ="table-responsive">
                  <table class="table table-striped" >
                    <thead class="card-header card-header-info">
                        <div class="ct-chart" id="#"></div>
                    <tr>
                      <th scope="col">Equipamento</th>
                      <th scope="col">Ferramenta</th>
                      <th scope="col" class="text-center">Alterar </th>
                      <th scope="col" class="text-center">Excluir </th>
                      <th scope="col" class="text-center">
                      <div class="text-right">
                    <a href="{% url 'manuti:cadastra_ferramenta' %}">
                        <button type="button" class="btn-primary bmd-btn-fab">
                            <i class="material-icons">add</i>
                        </button>
                    </a>
                </div>
                       </th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for ferramenta in ferramentas %}
                      <tr>
                        <th scope="row">{{ ferramenta.nome }}</th>
                        <td>{{ ferramenta.descricao }}</td>
                                                
                        
                        <td class="text-center">

                        <a href ="{% url 'manuti:atualiza_ferramenta' pk=ferramenta.id %}">
                        <button type="button" class="btn btn-info bmd-btn-fab">
                            <i class="material-icons">border_color</i>
                        </button>
                       </a>
                       <td class="text-center">

                        <a href="{% url 'manuti:deleta_ferramenta' pk=ferramenta.id %}">
                            <button type="button" class="btn btn-danger bmd-btn-fab">
                                <i class="material-icons">delete</i>
                            </button>
                            </a>      
                         </td>
                      </tr>

                    {% endfor %}
                    </tbody>
                  </table>
                  </div>
                 <hr />
              {% else %}
                <div class="text-center mt-5 mb-5 jumbotron">
                  <h5>Nenhuma <code>Ferramenta</code> cadastrada ainda.</h5>
                </div>
                <a href="{% url 'manuti:cadastra_ferramenta' %}">
                    <button type="button" class="btn btn-info bmd-btn-fab">
                        <i class="material-icons">add</i>
                    </button>
                </a>
              {% endif %}
                <hr />
               
              </div>
            </div>
          </div>
        </div>
      

{% endblock %}

supermanut/manuti/templates/manuti/listaSuprimento.html
{% extends "manuti/_layouts/indexMaterial.html" %}


{% block title %}Lista de Itens de Suprimento{% endblock %}

{% load primeira_letra %}

{% block conteudo %}

  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Lista de Itens de Suprimento</h5>

          {% if suprimentos|length > 0 %}
            <p class="card-text">
              Aqui está a lista de <code>Entrada e Saída </code> de Itens de Suprimento.
            </p>
          <div class ="table-responsive">
            <table class="table table-striped" >
              <thead class="card-header card-header-info">
                  <div class="ct-chart" id="#"></div>
              <tr>
                <th scope="col"></th>
                <th scope="col">Nome</th>
                <th scope="col">PN</th>
                <th scope="col">SN</th>
                <th scope="col">Recol</th>
                <th scope="col">E/S</th>
                <th scope="col" class="text-center">Ações</th>
              </tr>
              </thead>
              <tbody>
              {% for suprimento in suprimentos %}
                <tr>
                  <th scope="row">{{ suprimento.data}}</th>
                  <td>{{ suprimento.nome }}</td>
                  <td> {{suprimento.partnumber }}</td>
                  <td> {{suprimento.serialnumber }}</td>
                  <td> {{suprimento.recol}}</td>
                  <td> {{suprimento.opcaosup }}</td>
                  <td class="text-center">
                    <a href="{% url 'manuti:atualiza_suprimento' pk=suprimento.id %}">
                    <button type="button" class="btn btn-info bmd-btn-fab">
                        <i class="material-icons">border_color</i>
                    </button>
                    </a> 
                    <a href="{% url 'manuti:deleta_suprimento' pk=suprimento.id %}">
                    <button type="button" class="btn btn-danger bmd-btn-fab">
                        <i class="material-icons">delete</i>
                    </button>
                    </a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
        {% else %}
          <div class="text-center mt-5 mb-5 jumbotron">
            <h5>Nenhum <code>Item</code> registrado ainda.</h5>
          </div>
        {% endif %}
          <hr />
          <div class="text-right">
            <a href="{% url 'manuti:cadastra_suprimento' %}">
                <button type="button" class="btn btn-success bmd-btn-fab">
                    <i class="material-icons">add</i>
                </button>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}